/*  
[pt_BR] INICIO DO SISTEMA DE |CALCULADORA 2.O| 
[en_US] SYSTEM BEGIN FOR |CALCULATOR 2.0|


[pt_BR] DESC : ESTE SISTEMA FOI DESENVOLVIDO DURANTE O CURSO DE ESPECIALIZAÇÃO A JAVASCRIPT.
[en_US] DESC : THIS SYSTEM HAVE BEEN DEVELOPED DURING THE JAVASCRIPT ESPECIALIZATION COURSE.

[pt_BR] NOTE: SE VOCÊ TEM ALGUMA SUGESTÃO PARA MELHORAR O CÓDIGO, FAÇA UM 'COMMIT' E IREI IMPLEMENTAR.
[en_US] NOTE: IF YOU HAVE AN SUGESTION TO IMPROVE THE CODE, MAKE A 'COMIT' AND I'LL UPDATE.

Contact: (Github)
Author JavaScript code: @LucasMeloE4W

Contact: (Github)
Author SVG Image: @Hcodebr  -   https://www.hcodebr.com.br/


V: 1.0.0

[pt_BR] UPDATE: MARÇO DE 2020
[en_US] UPDATE: MARCH, 2020
*/

let calculator = new CalcController();

